### ISSUE TITLE
[Questoion] Which board will cover in this repo?

### ISSUE THREAD

**Issue by pino-kim** [alistair23/meta-pine64#1]
Dear MAINTAINER @alistair23

I just wonder which board cover in this github.
Because I buy some board at pine64 webpage(Maybe today hahaha)

So I leave some question here to you. 
Do you have the plan to cover Rockchip series board. 
Like Rock64, Rockpro64 board.

And Happy New Year. 
Thanks

**Comment by alistair23** [comment]
Hey, my plan at the moment is just to support the sopine64. I might extend that to the PinePhone if/when that comes out.

If anyone else wants to contribute I can help support the Rock64, but as I don't have one I don't think I'll add any support.

**Comment by pino-kim** [comment]
Dear @alistair23 
 
I have a few info about pinephone so search it.
And It will be a really nice idea. 

I see at the moment, your plan is supporting pinephone by sopine64.
I close this Question.

Thanks to reply
