### ISSUE TITLE
Pine A64+ support

### ISSUE THREAD

**Issue by lorenzo-arena** [alistair23/meta-pine64#18]
I am trying to build an image for a Pine A64+; using the LTS machine I can build successfully but on boot I get this error from the SPL:

```
U-Boot SPL 2021.01 (Jan 11 2021 - 18:11:43 +0000)
DRAM: 0 MiB
### ERROR ### Please RESET the board ###
```

I think it could be due to the face that while the + model uses DDR3 RAM, the LTS one uses LPDDR3. I that is wanted I can create a new machine, test it and make a pull request.

**Comment by alistair23** [comment]
You are probably gong to have to add a new board conf and specify at least a different u-boot config, probably also a different kernel DTS

**Comment by lorenzo-arena** [comment]
Closing as fixed by https://github.com/alistair23/meta-pine64/pull/19
