### ISSUE TITLE
trusted-firmware-a_%.bbappend no recipes available

### ISSUE THREAD

**Issue by EasyIP2023** [alistair23/meta-pine64#20]
What layer contains the original recipe? Can we add it to the README

**Comment by EasyIP2023** [comment]
Never mind think I found it. https://git.yoctoproject.org/cgit/cgit.cgi/meta-arm/tree/meta-arm/recipes-bsp?h=dunfell

**Comment by alistair23** [comment]
It's the meta-arm layer, it is listed as a dependency in the README: https://github.com/alistair23/meta-pine64#dependencies
