### ISSUE TITLE
Sopine build issue

### ISSUE THREAD

**Issue by legath** [alistair23/meta-pine64#23]
Very strange issue for MACHINE=sopine-a64
I have checked layer before **bitbake-layers add-layer**  and got the next log 
The same issue if trying just build. 
I have tried to update bbappend from mnainline meta-arm-bsp but nothing understand. 

_======================================================================
INFO: ERROR: test_world (common.CommonCheckLayer)
INFO: ----------------------------------------------------------------------
INFO: Traceback (most recent call last):
  File "/run/media/alexander/23a16ff3-da44-449e-b0ae-63c07d761023/poky/scripts/lib/checklayer/cases/common.py", line 44, in test_world
    get_signatures(self.td['builddir'], failsafe=False)
  File "/run/media/alexander/23a16ff3-da44-449e-b0ae-63c07d761023/poky/scripts/lib/checklayer/__init__.py", line 286, in get_signatures
    check_command('Generating signatures failed. This might be due to some parse error and/or general layer incompatibilities.',
  File "/run/media/alexander/23a16ff3-da44-449e-b0ae-63c07d761023/poky/scripts/lib/checklayer/__init__.py", line 261, in check_command
    raise RuntimeError(msg)
RuntimeError: Generating signatures failed. This might be due to some parse error and/or general layer incompatibilities.
Command: BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE BB_SIGNATURE_HANDLER" BB_SIGNATURE_HANDLER="OEBasicHash" bitbake -S none world
Output:
WARNING: Host distribution "manjaro" has not been validated with this version of the build system; you may possibly experience unexpected failures. It is recommended that you use a tested distribution.
Loading cache...done.
ERROR: No recipes in default available for:
  /run/media/alexander/23a16ff3-da44-449e-b0ae-63c07d761023/poky/meta-pine64/recipes-bsp/trusted-firmware-a/trusted-firmware-a_%.bbappend
Loaded 1473 entries from dependency cache.

Summary: There was 1 WARNING message shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code._

**Comment by legath** [comment]
shame on me , i did not add meta-arm layer. 
tried build as in example. 
can i make PR for pure example in readme?

**Comment by alistair23** [comment]
I'm glad you got it working. If you see any improvements that can be made to the README just go ahead and submit a PR
