### ISSUE TITLE
Linux Can not boot

### ISSUE THREAD

**Issue by 274336317** [alistair23/meta-pine64#5]
Firstly, Thanks for your great job!

I followed your guide "MACHINE=pine-a64-lts bitbake core-image-base ", and used this command "sudo dd if=core-image-base.wic of=/dev/sdbx" to install linux on SD CARD.
Then I powered on my pine64 board, The U-Boot could not find linux kenerl.
Can you give some advices?
Thanks!

**Comment by alistair23** [comment]
What image is u-boot looking for? What is contained inside your boot partition?

**Comment by 274336317** [comment]
Hi! Thanks for your reply!
Your layer works fine!
I'm sorry for my mistake. I removed meta-yocto-bsp from conf/bblayers.conf, so the uboot can not found linux kernel.
