### ISSUE TITLE
WARNING: High resolution timers not available

### ISSUE THREAD

**Issue by 274336317** [alistair23/meta-pine64#6]
I run cyclictest on pine64.After launch cyclictest, it printed the following warning:
**WARNING: High resolution timers not available**
I reviewed the /proc/config.gz, and the "CONFIG_HIGH_RES_TIMERS=y" was set.

Can you give some advice?

**Comment by alistair23** [comment]
I'm sorry, I'm not sure. You should start by grepping that string in the kernel and see what is causing the warning.

**Comment by 274336317** [comment]
I switched from 5.3.0 to linux 5.2.14, the warning dispeared.

**Comment by alistair23** [comment]
5.2 is getting close to end of life, so it's still probably worth investigating what changed.
