### ISSUE TITLE
[Help] How do I get the output onto an SD card

### ISSUE THREAD

**Issue by bitbrain-za** [alistair23/meta-pine64#7]
Seems like it should be a simple thing but having gone through the wic documentation I still haven't a clue.

`MACHINE=pine-a64-lts bitbake core-image-weston`

Ran fine and I have a tmp/deploy/images directory with what looks like all the necessary bits. But I cannot for the life of me figure out how to get it into the SD card.

**Comment by alistair23** [comment]
You need to `dd` the `*wic` image to an SD card.

Something like this should work:
```shell
sudo dd if=./build/tmp-glibc/images/pine-a64-lts/core-image*.wic of=/dev/sdX bs=4M iflag=fullblock oflag=direct conv=fsync status=progress
```

**Comment by alistair23** [comment]
You can also use bmaptool, see https://www.yoctoproject.org/docs/2.3/dev-manual/dev-manual.html#flashing-images-using-bmaptool for details

**Comment by bitbrain-za** [comment]
Thank you!

**Comment by alistair23** [comment]
If you want can you send a PR to update the README? That way others can benefit from this as well.

**Comment by bitbrain-za** [comment]
> If you want can you send a PR to update the README? That way others can benefit from this as well.

Will do so after checking it all works.
